/*global_inventory table schema*/
create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_red_ml integer null,
    gold integer null,
    num_blue_ml integer null,
    num_green_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

/*Potions table schema*/
create table
  public.potions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    red_ml integer null,
    green_ml integer null,
    blue_ml integer null,
    sku text null,
    name text null,
    price integer null,
    quantity integer null,
    dark_ml integer null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;

  /*initial population of potions table*/
  INSERT INTO potions
  (red_ml, green_ml, blue_ml, dark_ml, sku, name, price, quantity)
  VALUES
  (50, 50, 0, 0, 'YELLOW_POTION_0', 'yellow potion', 50, 0),
  (50, 0, 50, 0, 'PURPLE_POTION_0', 'purple potion', 50, 0),
  (0, 50, 50, 0, 'TEAL_POTION_0', 'teal potion', 50, 0),
  (100, 0, 0, 0, 'RED_POTION_0', 'red potion', 50, 0),
  (0, 100, 0, 0, 'GREEN_POTION_0', 'green potion', 50, 0),
  (0, 0, 100, 0, 'BLUE_POTION_0', 'blue potion', 50, 0)

/*cart_items table schema*/
create table
  public.cart_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint null,
    potion_id bigint null,
    quantity integer null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;

/*carts table schema*/
  create table
  public.carts (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;